// Seed data transcribed from the (now removed) static data modules
// src/data/companies.ts and src/data/jobs.ts. Imported by prisma/seed.mjs
// so companies + jobs are seeded into PostgreSQL with isDemo=false.

export const SEED_COMPANIES = [
  // QUICK COMMERCE / DELIVERY / STARTUPS
  { name: "Blinkit", industry: "Quick Commerce", location: "Gurugram", companySize: "1,001-5,000", website: "https://blinkit.com", description: "India's largest quick commerce platform delivering groceries in 10 minutes.", founded: "2013" },
  { name: "BigBasket", industry: "E-commerce", location: "Bengaluru", companySize: "5,001-10,000", website: "https://bigbasket.com", description: "Online grocery and fresh produce delivery platform.", founded: "2011" },
  { name: "Meesho", industry: "E-commerce", location: "Bengaluru", companySize: "1,001-5,000", website: "https://meesho.com", description: "Social commerce platform enabling small businesses to sell online.", founded: "2015" },
  { name: "Rapido", industry: "Mobility", location: "Bengaluru", companySize: "501-1,000", website: "https://rapido.bike", description: "India's largest bike taxi and delivery platform.", founded: "2015" },
  { name: "Porter", industry: "Logistics", location: "Mumbai", companySize: "501-1,000", website: "https://porter.in", description: "On-demand mini truck and packing-moving platform for intra-city logistics.", founded: "2014" },
  { name: "Ather Energy", industry: "Electric Vehicles", location: "Bengaluru", companySize: "1,001-5,000", website: "https://atherenergy.com", description: "Electric scooter manufacturer building intelligent EV infrastructure.", founded: "2013" },
  { name: "CRED", industry: "Fintech", location: "Bengaluru", companySize: "501-1,000", website: "https://cred.club", description: "Rewards-based platform for credit card bill payments and credit scores.", founded: "2018" },
  { name: "Slice", industry: "Fintech", location: "Bengaluru", companySize: "501-1,000", website: "https://slicelife.com", description: "Digital-first credit card and spending platform for young Indians.", founded: "2016" },
  { name: "Jupiter", industry: "Fintech", location: "Bengaluru", companySize: "201-500", website: "https://jupiter.money", description: "Digital banking platform offering smart savings and money management.", founded: "2019" },
  { name: "Fi", industry: "Fintech", location: "Bengaluru", companySize: "201-500", website: "https://fi.money", description: "Neo-banking platform with smart spending and savings features.", founded: "2019" },
  { name: "Navi", industry: "Fintech", location: "Bengaluru", companySize: "501-1,000", website: "https://navi.com", description: "Digital financial services company offering loans, insurance and investments.", founded: "2018" },
  { name: "KreditBee", industry: "Fintech", location: "Bengaluru", companySize: "501-1,000", website: "https://kreditbee.in", description: "Digital lending platform for personal loans and credit lines.", founded: "2017" },
  { name: "Zepto", industry: "Quick Commerce", location: "Mumbai", companySize: "1,001-5,000", website: "https://zeptonow.com", description: "10-minute grocery delivery startup across Indian metros.", founded: "2021" },
  { name: "Swiggy", industry: "Food Delivery", location: "Bengaluru", companySize: "5,001-10,000", website: "https://swiggy.com", description: "India's leading food ordering and delivery platform.", founded: "2014" },
  { name: "Zomato", industry: "Food Delivery", location: "Gurugram", companySize: "5,001-10,000", website: "https://zomato.com", description: "Food delivery and restaurant discovery platform.", founded: "2008" },
  { name: "Uber", industry: "Mobility", location: "San Francisco", companySize: "10,001+", website: "https://uber.com", description: "Global ridesharing and mobility platform.", founded: "2009" },
  { name: "Ola", industry: "Mobility", location: "Bengaluru", companySize: "5,001-10,000", website: "https://olacabs.com", description: "India's ride-hailing and mobility platform.", founded: "2010" },
  { name: "Urban Company", industry: "Services Marketplace", location: "Gurugram", companySize: "1,001-5,000", website: "https://urbancompany.com", description: "Home services marketplace for skilled professionals.", founded: "2014" },
  { name: "PhonePe", industry: "Fintech", location: "Bengaluru", companySize: "1,001-5,000", website: "https://phonepe.com", description: "UPI payments and digital wallet platform.", founded: "2015" },
  { name: "Paytm", industry: "Fintech", location: "Noida", companySize: "5,001-10,000", website: "https://paytm.com", description: "Financial services and payments platform.", founded: "2010" },
  { name: "Razorpay", industry: "Fintech", location: "Bengaluru", companySize: "1,001-5,000", website: "https://razorpay.com", description: "Payment gateway and financial solutions platform.", founded: "2014" },
  { name: "Groww", industry: "Fintech", location: "Bengaluru", companySize: "1,001-5,000", website: "https://groww.in", description: "Investment and stock trading platform for retail investors.", founded: "2016" },
  { name: "Policybazaar", industry: "Fintech", location: "Gurugram", companySize: "5,001-10,000", website: "https://policybazaar.com", description: "Insurance comparison and buying platform.", founded: "2008" },
  { name: "Dream11", industry: "Fantasy Sports", location: "Mumbai", companySize: "501-1,000", website: "https://dream11.com", description: "India's leading fantasy sports platform.", founded: "2008" },
  { name: "Lenskart", industry: "E-commerce", location: "Gurugram", companySize: "5,001-10,000", website: "https://lenskart.com", description: "Eyewear brand offering glasses and contact lenses online and offline.", founded: "2010" },
  { name: "Delhivery", industry: "Logistics", location: "Gurugram", companySize: "10,001+", website: "https://delhivery.com", description: "Fulfillment and logistics services platform.", founded: "2011" },
  { name: "Udaan", industry: "B2B Commerce", location: "Bengaluru", companySize: "1,001-5,000", website: "https://udaan.com", description: "B2B wholesale trading platform connecting buyers and sellers.", founded: "2016" },
  { name: "Dunzo", industry: "Quick Commerce", location: "Bengaluru", companySize: "501-1,000", website: "https://dunzo.in", description: "Hyperlocal delivery and errand app for everyday tasks.", founded: "2014" },
  { name: "Nykaa", industry: "E-commerce", location: "Mumbai", companySize: "1,001-5,000", website: "https://nykaa.com", description: "Beauty and wellness e-commerce and retail brand.", founded: "2012" },
  { name: "Unacademy", industry: "EdTech", location: "Bengaluru", companySize: "5,001-10,000", website: "https://unacademy.com", description: "Online learning platform for exam preparation and skill development.", founded: "2015" },
  // TELECOM / ELECTRONICS
  { name: "Bharti Airtel", industry: "Telecom", location: "New Delhi", companySize: "10,001+", website: "https://airtel.in", description: "India's largest telecom operator and digital services provider.", founded: "1995" },
  { name: "Vodafone Idea", industry: "Telecom", location: "Mumbai", companySize: "10,001+", website: "https://vodafoneidea.com", description: "Telecom service provider serving millions across India.", founded: "2018" },
  { name: "Tata Communications", industry: "Telecom", location: "Mumbai", companySize: "5,001-10,000", website: "https://tatacommunications.com", description: "Global digital infrastructure provider for digital enterprises.", founded: "1986" },
  { name: "Samsung", industry: "Consumer Electronics", location: "New Delhi", companySize: "10,001+", website: "https://samsung.com", description: "Global leader in consumer electronics and mobile devices.", founded: "1938" },
  { name: "LG Electronics", industry: "Consumer Electronics", location: "Seoul", companySize: "10,001+", website: "https://lg.com", description: "Global electronics and appliance manufacturer.", founded: "1958" },
  { name: "Sony", industry: "Consumer Electronics", location: "Tokyo", companySize: "10,001+", website: "https://sony.com", description: "Global technology and entertainment conglomerate.", founded: "1946" },
  { name: "Xiaomi", industry: "Consumer Electronics", location: "Bengaluru", companySize: "5,001-10,000", website: "https://mi.com", description: "Smartphone and smart device manufacturer with AIoT ecosystem.", founded: "2010" },
  { name: "Lenovo", industry: "Technology Hardware", location: "Morrisville", companySize: "10,001+", website: "https://lenovo.com", description: "Global PC and smart device manufacturer.", founded: "1984" },
  { name: "ASUS", industry: "Technology Hardware", location: "Taipei", companySize: "10,001+", website: "https://asus.com", description: "Computer hardware and electronics company.", founded: "1989" },
  { name: "OnePlus", industry: "Consumer Electronics", location: "Shenzhen", companySize: "1,001-5,000", website: "https://oneplus.com", description: "Premium smartphone brand known for flagship devices.", founded: "2013" },
  { name: "Panasonic", industry: "Consumer Electronics", location: "Osaka", companySize: "10,001+", website: "https://panasonic.com", description: "Global electronics and appliances manufacturer.", founded: "1918" },
  { name: "Philips", industry: "Consumer Electronics", location: "Amsterdam", companySize: "10,001+", website: "https://philips.com", description: "Health technology and consumer products company.", founded: "1891" },
  { name: "Nokia", industry: "Telecom", location: "Espoo", companySize: "10,001+", website: "https://nokia.com", description: "Network infrastructure and technology leader.", founded: "1865" },
  { name: "Ericsson", industry: "Telecom", location: "Stockholm", companySize: "10,001+", website: "https://ericsson.com", description: "Networking and telecommunications equipment leader.", founded: "1876" },
  { name: "HP", industry: "Technology Hardware", location: "Palo Alto", companySize: "10,001+", website: "https://hp.com", description: "Personal computing and printing solutions company.", founded: "1939" },
  { name: "Dell Technologies", industry: "Technology Hardware", location: "Round Rock", companySize: "10,001+", website: "https://dell.com", description: "Computer technology and IT infrastructure provider.", founded: "1984" },
  { name: "Intel", industry: "Semiconductors", location: "Santa Clara", companySize: "10,001+", website: "https://intel.com", description: "Semiconductor and processor technology leader.", founded: "1968" },
  { name: "Qualcomm", industry: "Semiconductors", location: "San Diego", companySize: "10,001+", website: "https://qualcomm.com", description: "Wireless technology and semiconductor pioneer.", founded: "1985" },
  { name: "Cisco", industry: "Networking", location: "San Jose", companySize: "10,001+", website: "https://cisco.com", description: "Networking and cybersecurity technology leader.", founded: "1984" },
  { name: "Motorola", industry: "Telecom", location: "Schaumburg", companySize: "5,001-10,000", website: "https://motorola.com", description: "Telecommunications and mobile device manufacturer.", founded: "1928" },
  // CONSULTING / PROFESSIONAL SERVICES
  { name: "Deloitte", industry: "Consulting", location: "New York", companySize: "10,001+", website: "https://deloitte.com", description: "Global leader in audit, consulting, tax and advisory services.", founded: "1845" },
  { name: "EY", industry: "Consulting", location: "London", companySize: "10,001+", website: "https://ey.com", description: "Global professional services firm in assurance, tax and advisory.", founded: "1989" },
  { name: "PwC", industry: "Consulting", location: "London", companySize: "10,001+", website: "https://pwc.com", description: "Global professional services network in audit and advisory.", founded: "1998" },
  { name: "KPMG", industry: "Consulting", location: "Amstelveen", companySize: "10,001+", website: "https://kpmg.com", description: "Global professional services firm in audit, tax and advisory.", founded: "1987" },
  { name: "BCG", industry: "Consulting", location: "Boston", companySize: "10,001+", website: "https://bcg.com", description: "Global management consulting firm.", founded: "1963" },
  { name: "McKinsey & Company", industry: "Consulting", location: "New York", companySize: "10,001+", website: "https://mckinsey.com", description: "Global management consulting firm for leading organizations.", founded: "1926" },
  { name: "Bain & Company", industry: "Consulting", location: "Boston", companySize: "5,001-10,000", website: "https://bain.com", description: "Global management consulting firm.", founded: "1973" },
  { name: "Accenture", industry: "Consulting", location: "Dublin", companySize: "10,001+", website: "https://accenture.com", description: "Global professional services company in consulting and technology.", founded: "1989" },
  { name: "Grant Thornton", industry: "Consulting", location: "Chicago", companySize: "10,001+", website: "https://grantthornton.com", description: "Global accounting and advisory firm.", founded: "1980" },
  { name: "Protiviti", industry: "Consulting", location: "Menlo Park", companySize: "5,001-10,000", website: "https://protiviti.com", description: "Global consulting firm in risk and advisory.", founded: "2002" },
  { name: "Oliver Wyman", industry: "Consulting", location: "New York", companySize: "5,001-10,000", website: "https://oliverwyman.com", description: "Global management consulting firm.", founded: "1984" },
  { name: "Gartner", industry: "Consulting", location: "Stamford", companySize: "10,001+", website: "https://gartner.com", description: "Global research and advisory company for technology.", founded: "1979" },
  { name: "Capgemini", industry: "IT Services", location: "Paris", companySize: "10,001+", website: "https://capgemini.com", description: "Global IT services and consulting company.", founded: "1967" },
  { name: "Cognizant", industry: "IT Services", location: "Teaneck", companySize: "10,001+", website: "https://cognizant.com", description: "Global IT services and consulting company.", founded: "1994" },
  { name: "IBM Consulting", industry: "IT Services", location: "New York", companySize: "10,001+", website: "https://ibm.com", description: "Global technology and consulting company.", founded: "1911" },
  { name: "Genpact", industry: "IT Services", location: "New York", companySize: "10,001+", website: "https://genpact.com", description: "Professional services and digital transformation partner.", founded: "1997" },
  { name: "Infosys Consulting", industry: "IT Services", location: "Bengaluru", companySize: "10,001+", website: "https://infosys.com", description: "Global IT services and consulting company.", founded: "1981" },
  { name: "TCS", industry: "IT Services", location: "Mumbai", companySize: "10,001+", website: "https://tcs.com", description: "India's largest IT services and consulting company.", founded: "1968" },
  { name: "Wipro", industry: "IT Services", location: "Bengaluru", companySize: "10,001+", website: "https://wipro.com", description: "Global IT services, consulting and business process company.", founded: "1945" },
  { name: "HCLTech", industry: "IT Services", location: "Noida", companySize: "10,001+", website: "https://hcltech.com", description: "Global technology company delivering digital transformation.", founded: "1976" },
  // FINANCE / PAYMENTS
  { name: "American Express", industry: "Finance", location: "New York", companySize: "10,001+", website: "https://americanexpress.com", description: "Global financial services and card company.", founded: "1850" },
  { name: "Mastercard", industry: "Payments", location: "Purchase", companySize: "10,001+", website: "https://mastercard.com", description: "Global payment and technology company.", founded: "1966" },
  { name: "Visa", industry: "Payments", location: "San Francisco", companySize: "10,001+", website: "https://visa.com", description: "Global digital payment technology company.", founded: "1958" },
  { name: "JPMorgan Chase", industry: "Banking", location: "New York", companySize: "10,001+", website: "https://jpmorganchase.com", description: "Global financial services and banking leader.", founded: "2000" },
  { name: "Goldman Sachs", industry: "Banking", location: "New York", companySize: "10,001+", website: "https://goldmansachs.com", description: "Global investment banking and securities firm.", founded: "1869" },
  { name: "Morgan Stanley", industry: "Banking", location: "New York", companySize: "10,001+", website: "https://morganstanley.com", description: "Global investment banking and wealth management firm.", founded: "1935" },
  { name: "Citi", industry: "Banking", location: "New York", companySize: "10,001+", website: "https://citigroup.com", description: "Global financial services and banking corporation.", founded: "1812" },
  { name: "Barclays", industry: "Banking", location: "London", companySize: "10,001+", website: "https://barclays.com", description: "British multinational investment bank.", founded: "1690" },
  { name: "HSBC", industry: "Banking", location: "London", companySize: "10,001+", website: "https://hsbc.com", description: "Global banking and financial services organization.", founded: "1865" },
  { name: "PayPal", industry: "Payments", location: "San Jose", companySize: "10,001+", website: "https://paypal.com", description: "Global online payments system.", founded: "1998" },
  { name: "Stripe", industry: "Payments", location: "San Francisco", companySize: "5,001-10,000", website: "https://stripe.com", description: "Online payment processing and fintech platform.", founded: "2010" },
  { name: "Block", industry: "Fintech", location: "Oakland", companySize: "5,001-10,000", website: "https://block.xyz", description: "Global fintech company behind Square and Cash App.", founded: "2009" },
  { name: "Coinbase", industry: "Crypto", location: "San Francisco", companySize: "1,001-5,000", website: "https://coinbase.com", description: "Leading cryptocurrency exchange platform.", founded: "2012" },
  { name: "Wise", industry: "Fintech", location: "London", companySize: "5,001-10,000", website: "https://wise.com", description: "Global money transfer platform with transparent rates.", founded: "2011" },
  { name: "Revolut", industry: "Fintech", location: "London", companySize: "5,001-10,000", website: "https://revolut.com", description: "Digital banking and financial super app.", founded: "2015" },
  // SAAS / SOFTWARE / TECHNOLOGY
  { name: "Shopify", industry: "SaaS", location: "Ottawa", companySize: "10,001+", website: "https://shopify.com", description: "E-commerce platform for online stores and retail point-of-sale.", founded: "2006" },
  { name: "Zoom", industry: "SaaS", location: "San Jose", companySize: "5,001-10,000", website: "https://zoom.us", description: "Video communication and collaboration platform.", founded: "2011" },
  { name: "Dropbox", industry: "SaaS", location: "San Francisco", companySize: "1,001-5,000", website: "https://dropbox.com", description: "Cloud storage and file sharing service.", founded: "2007" },
  { name: "DocuSign", industry: "SaaS", location: "San Francisco", companySize: "5,001-10,000", website: "https://docusign.com", description: "Electronic signature and agreement management platform.", founded: "2003" },
  { name: "Twilio", industry: "SaaS", location: "San Francisco", companySize: "5,001-10,000", website: "https://twilio.com", description: "Cloud communications platform for messaging and voice.", founded: "2008" },
  { name: "HubSpot", industry: "SaaS", location: "Cambridge", companySize: "5,001-10,000", website: "https://hubspot.com", description: "Customer relationship management and marketing platform.", founded: "2006" },
  { name: "Autodesk", industry: "Software", location: "San Francisco", companySize: "10,001+", website: "https://autodesk.com", description: "Software for design, engineering and entertainment.", founded: "1982" },
  { name: "Figma", industry: "SaaS", location: "San Francisco", companySize: "501-1,000", website: "https://figma.com", description: "Collaborative interface design and prototyping tool.", founded: "2012" },
  { name: "Canva", industry: "SaaS", location: "Sydney", companySize: "5,001-10,000", website: "https://canva.com", description: "Online graphic design and visual communication platform.", founded: "2013" },
  { name: "GitLab", industry: "Developer Tools", location: "San Francisco", companySize: "1,001-5,000", website: "https://gitlab.com", description: "DevOps and CI/CD platform in a single application.", founded: "2014" },
  { name: "Cloudflare", industry: "Infrastructure", location: "San Francisco", companySize: "1,001-5,000", website: "https://cloudflare.com", description: "Content delivery network and internet security services.", founded: "2009" },
  { name: "MongoDB", industry: "Database", location: "New York", companySize: "5,001-10,000", website: "https://mongodb.com", description: "Leading NoSQL database platform.", founded: "2007" },
  { name: "Elastic", industry: "Software", location: "Mountain View", companySize: "1,001-5,000", website: "https://elastic.co", description: "Search and analytics company behind Elasticsearch.", founded: "2012" },
  { name: "Red Hat", industry: "Software", location: "Raleigh", companySize: "10,001+", website: "https://redhat.com", description: "Open source software and enterprise Linux provider.", founded: "1993" },
  { name: "OpenText", industry: "Software", location: "Waterloo", companySize: "10,001+", website: "https://opentext.com", description: "Enterprise information management software company.", founded: "1991" },
  { name: "Atlassian", industry: "SaaS", location: "Sydney", companySize: "5,001-10,000", website: "https://atlassian.com", description: "Collaboration software for teams including Jira and Confluence.", founded: "2002" },
  { name: "Salesforce", industry: "SaaS", location: "San Francisco", companySize: "10,001+", website: "https://salesforce.com", description: "Cloud-based customer relationship management platform.", founded: "1999" },
  { name: "Oracle", industry: "Software", location: "Austin", companySize: "10,001+", website: "https://oracle.com", description: "Enterprise software and cloud infrastructure provider.", founded: "1977" },
  { name: "SAP", industry: "Software", location: "Walldorf", companySize: "10,001+", website: "https://sap.com", description: "Enterprise resource planning and business software.", founded: "1972" },
  { name: "Adobe", industry: "Software", location: "San Jose", companySize: "10,001+", website: "https://adobe.com", description: "Creative software and digital experience company.", founded: "1982" },
  { name: "Microsoft", industry: "Technology", location: "Redmond", companySize: "10,001+", website: "https://microsoft.com", description: "Global technology company for software and cloud services.", founded: "1975" },
  { name: "Google", industry: "Technology", location: "Mountain View", companySize: "10,001+", website: "https://google.com", description: "Global technology company for search, cloud and AI.", founded: "1998" },
  { name: "Amazon", industry: "Technology", location: "Seattle", companySize: "10,001+", website: "https://amazon.com", description: "Global e-commerce and cloud computing company.", founded: "1994" },
  { name: "Meta", industry: "Technology", location: "Menlo Park", companySize: "10,001+", website: "https://meta.com", description: "Global technology company behind Facebook, Instagram and WhatsApp.", founded: "2004" },
  { name: "NVIDIA", industry: "Semiconductors", location: "Santa Clara", companySize: "10,001+", website: "https://nvidia.com", description: "Global leader in graphics processing and AI computing.", founded: "1993" },
  // INDIAN IT / PRODUCT COMPANIES
  { name: "Zoho", industry: "SaaS", location: "Chennai", companySize: "10,001+", website: "https://zoho.com", description: "Software company offering cloud-based business apps.", founded: "1996" },
  { name: "Freshworks", industry: "SaaS", location: "San Mateo", companySize: "1,001-5,000", website: "https://freshworks.com", description: "Software company for customer engagement and support.", founded: "2010" },
  { name: "BrowserStack", industry: "Developer Tools", location: "Dublin", companySize: "501-1,000", website: "https://browserstack.com", description: "Cross-browser testing platform for developers.", founded: "2011" },
  { name: "Postman", industry: "Developer Tools", location: "San Francisco", companySize: "501-1,000", website: "https://postman.com", description: "API development and testing platform.", founded: "2014" },
  { name: "Zerodha", industry: "Fintech", location: "Bengaluru", companySize: "1,001-5,000", website: "https://zerodha.com", description: "India's largest retail stock broking platform.", founded: "2010" },
  { name: "MPL", industry: "Gaming", location: "Bengaluru", companySize: "501-1,000", website: "https://mpl.live", description: "Mobile gaming and esports platform.", founded: "2018" },
  { name: "CredAvenue", industry: "Fintech", location: "Chennai", companySize: "201-500", website: "https://credavenue.com", description: "Debt market platform for institutional lending.", founded: "2020" },
  { name: "Chargebee", industry: "SaaS", location: "Chennai", companySize: "501-1,000", website: "https://chargebee.com", description: "Subscription billing and revenue management platform.", founded: "2011" },
  { name: "InMobi", industry: "AdTech", location: "Bengaluru", companySize: "1,001-5,000", website: "https://inmobi.com", description: "Mobile advertising and marketing technology platform.", founded: "2007" },
  { name: "ShareChat", industry: "Social Media", location: "Bengaluru", companySize: "501-1,000", website: "https://sharechat.com", description: "Indian language social media platform.", founded: "2015" },
  { name: "Moj", industry: "Social Media", location: "Bengaluru", companySize: "501-1,000", website: "https://moj.com", description: "Short-form video platform in Indian languages.", founded: "2020" },
  // E-COMMERCE / RETAIL
  { name: "Flipkart", industry: "E-commerce", location: "Bengaluru", companySize: "10,001+", website: "https://flipkart.com", description: "India's leading e-commerce marketplace.", founded: "2007" },
  { name: "Myntra", industry: "E-commerce", location: "Bengaluru", companySize: "1,001-5,000", website: "https://myntra.com", description: "Fashion and lifestyle e-commerce platform.", founded: "2007" },
  { name: "AJIO", industry: "E-commerce", location: "Bengaluru", companySize: "1,001-5,000", website: "https://ajio.com", description: "Fashion and lifestyle e-commerce platform by Reliance.", founded: "2016" },
  { name: "Tata Digital", industry: "Technology", location: "Mumbai", companySize: "501-1,000", website: "https://tata.com", description: "Digital arm of the Tata Group building consumer services.", founded: "2019" },
  { name: "Reliance Retail", industry: "Retail", location: "Mumbai", companySize: "10,001+", website: "https://ril.com", description: "India's largest retail business.", founded: "2006" },
  { name: "Decathlon", industry: "Retail", location: "Lille", companySize: "10,001+", website: "https://decathlon.com", description: "Global sporting goods retailer.", founded: "1976" },
  { name: "IKEA", industry: "Retail", location: "Delft", companySize: "10,001+", website: "https://ikea.com", description: "Global furniture and home goods retailer.", founded: "1943" },
  { name: "Walmart", industry: "Retail", location: "Bentonville", companySize: "10,001+", website: "https://walmart.com", description: "Global retail and e-commerce corporation.", founded: "1962" },
  { name: "Costco", industry: "Retail", location: "Issaquah", companySize: "10,001+", website: "https://costco.com", description: "Membership warehouse club and retailer.", founded: "1976" },
  // AUTOMOTIVE / MOBILITY
  { name: "Tata Motors", industry: "Automotive", location: "Mumbai", companySize: "10,001+", website: "https://tatamotors.com", description: "Indian automotive manufacturer of cars, trucks and EVs.", founded: "1945" },
  { name: "Mahindra", industry: "Automotive", location: "Mumbai", companySize: "10,001+", website: "https://mahindra.com", description: "Indian automobile and technology conglomerate.", founded: "1945" },
  { name: "Maruti Suzuki", industry: "Automotive", location: "New Delhi", companySize: "10,001+", website: "https://marutisuzuki.com", description: "India's largest passenger car manufacturer.", founded: "1981" },
  { name: "Hyundai", industry: "Automotive", location: "Seoul", companySize: "10,001+", website: "https://hyundai.com", description: "Global automobile manufacturer.", founded: "1967" },
  { name: "Toyota", industry: "Automotive", location: "Toyota City", companySize: "10,001+", website: "https://toyota.com", description: "Global automobile manufacturer.", founded: "1937" },
  { name: "Mercedes-Benz", industry: "Automotive", location: "Stuttgart", companySize: "10,001+", website: "https://mercedes-benz.com", description: "Luxury automobile manufacturer.", founded: "1926" },
  { name: "BMW", industry: "Automotive", location: "Munich", companySize: "10,001+", website: "https://bmw.com", description: "Luxury automobile and motorcycle manufacturer.", founded: "1916" },
  { name: "Volkswagen", industry: "Automotive", location: "Wolfsburg", companySize: "10,001+", website: "https://volkswagen.com", description: "Global automobile manufacturer.", founded: "1937" },
  { name: "Tesla", industry: "Automotive", location: "Austin", companySize: "10,001+", website: "https://tesla.com", description: "Electric vehicle and clean energy company.", founded: "2003" },
  { name: "Ola Electric", industry: "Electric Vehicles", location: "Bengaluru", companySize: "1,001-5,000", website: "https://olaelectric.com", description: "Electric vehicle manufacturer and mobility technology.", founded: "2017" },
  // MEDIA / ENTERTAINMENT
  { name: "Netflix", industry: "Media", location: "Los Gatos", companySize: "10,001+", website: "https://netflix.com", description: "Global streaming entertainment service.", founded: "1997" },
  { name: "Disney", industry: "Media", location: "Burbank", companySize: "10,001+", website: "https://disney.com", description: "Global entertainment and media conglomerate.", founded: "1923" },
  { name: "Warner Bros. Discovery", industry: "Media", location: "New York", companySize: "10,001+", website: "https://wbd.com", description: "Global media and entertainment company.", founded: "2022" },
  { name: "Spotify", industry: "Music Streaming", location: "Stockholm", companySize: "5,001-10,000", website: "https://spotify.com", description: "Global music streaming platform.", founded: "2006" },
  { name: "Sony Pictures", industry: "Media", location: "Culver City", companySize: "5,001-10,000", website: "https://sonypictures.com", description: "Global film and television studio.", founded: "1987" },
  { name: "YouTube", industry: "Media", location: "San Bruno", companySize: "5,001-10,000", website: "https://youtube.com", description: "Global video sharing and streaming platform.", founded: "2005" },
  { name: "Prime Video", industry: "Media", location: "Seattle", companySize: "5,001-10,000", website: "https://primevideo.com", description: "Streaming video service by Amazon.", founded: "2006" },
  { name: "JioCinema", industry: "Media", location: "Mumbai", companySize: "1,001-5,000", website: "https://jiocinema.com", description: "Indian streaming platform by Reliance Jio.", founded: "2016" },
  { name: "Hotstar", industry: "Media", location: "Mumbai", companySize: "1,001-5,000", website: "https://hotstar.com", description: "Indian streaming platform for live sports and entertainment.", founded: "2015" },
];

// Additional reputable companies to exceed 150 unique records
export const ADDITIONAL_COMPANIES = [
  { name: "LinkedIn", industry: "SaaS", location: "Sunnyvale", companySize: "10,001+", website: "https://linkedin.com", description: "Professional networking platform.", founded: "2003" },
  { name: "Airbnb", industry: "Travel", location: "San Francisco", companySize: "5,001-10,000", website: "https://airbnb.com", description: "Online marketplace for lodging and experiences.", founded: "2008" },
  { name: "Binance", industry: "Crypto", location: "Mumbai", companySize: "5,001-10,000", website: "https://binance.com", description: "Global cryptocurrency exchange.", founded: "2017" },
  { name: "Tinder", industry: "SaaS", location: "West Hollywood", companySize: "501-1,000", website: "https://tinder.com", description: "Dating and social discovery app.", founded: "2012" },
  { name: "Jio", industry: "Telecom", location: "Mumbai", companySize: "10,001+", website: "https://jio.com", description: "Indian telecom and digital services provider.", founded: "2007" },
  { name: "Titan", industry: "Retail", location: "Bengaluru", companySize: "5,001-10,000", website: "https://titancompany.in", description: "Indian luxury and lifestyle accessories brand.", founded: "1984" },
  { name: "Zara", industry: "Retail", location: "Arteixo", companySize: "10,001+", website: "https://zara.com", description: "Global fashion and clothing retailer.", founded: "1975" },
  { name: "Puma", industry: "Retail", location: "Herzogenaurach", companySize: "10,001+", website: "https://puma.com", description: "Global sportswear and footwear brand.", founded: "1948" },
  { name: "Nike", industry: "Retail", location: "Beaverton", companySize: "10,001+", website: "https://nike.com", description: "Global sportswear and athletic brand.", founded: "1964" },
  { name: "Adidas", industry: "Retail", location: "Herzogenaurach", companySize: "10,001+", website: "https://adidas.com", description: "Global sportswear and athletic brand.", founded: "1949" },
  { name: "UL", industry: "Consulting", location: "Gurugram", companySize: "10,001+", website: "https://ul.com", description: "Global safety science and testing company.", founded: "1894" },
  { name: "Bosch", industry: "Automotive", location: "Stuttgart", companySize: "10,001+", website: "https://bosch.com", description: "Global technology and engineering company.", founded: "1886" },
  { name: "Siemens", industry: "Technology", location: "Munich", companySize: "10,001+", website: "https://siemens.com", description: "Global technology and industrial conglomerate.", founded: "1847" },
  { name: "Cisco India", industry: "Networking", location: "Bengaluru", companySize: "5,001-10,000", website: "https://cisco.com", description: "Networking and cybersecurity technology leader.", founded: "1984" },
  { name: "Kotak Mahindra Bank", industry: "Banking", location: "Mumbai", companySize: "10,001+", website: "https://kotak.com", description: "Indian banking and financial services group.", founded: "1985" },
  { name: "HDFC Bank", industry: "Banking", location: "Mumbai", companySize: "10,001+", website: "https://hdfcbank.com", description: "India's largest private sector bank.", founded: "1994" },
  { name: "ICICI Bank", industry: "Banking", location: "Mumbai", companySize: "10,001+", website: "https://icicibank.com", description: "Indian private sector bank.", founded: "1994" },
  { name: "Axis Bank", industry: "Banking", location: "Mumbai", companySize: "10,001+", website: "https://axisbank.com", description: "Indian private sector bank.", founded: "1993" },
  { name: "Deloitte Digital", industry: "Consulting", location: "Bengaluru", companySize: "10,001+", website: "https://deloitte.com", description: "Digital consulting arm of Deloitte.", founded: "2012" },
  { name: "Infosys", industry: "IT Services", location: "Bengaluru", companySize: "10,001+", website: "https://infosys.com", description: "Global IT services and consulting company.", founded: "1981" },
  { name: "Adani", industry: "Conglomerate", location: "Ahmedabad", companySize: "10,001+", website: "https://adanienterprises.com", description: "Indian multinational conglomerate.", founded: "1988" },
  { name: "Reliance Industries", industry: "Conglomerate", location: "Mumbai", companySize: "10,001+", website: "https://ril.com", description: "India's largest conglomerate.", founded: "1966" },
  { name: "Bajaj Finserv", industry: "Finance", location: "Pune", companySize: "5,001-10,000", website: "https://bajajfinserv.in", description: "Indian financial services company.", founded: "2007" },
  { name: "Hindustan Unilever", industry: "FMCG", location: "Mumbai", companySize: "10,001+", website: "https://hul.co.in", description: "Indian consumer goods company.", founded: "1933" },
  { name: "ITC", industry: "FMCG", location: "Kolkata", companySize: "10,001+", website: "https://itcportal.com", description: "Indian consumer goods and conglomerate company.", founded: "1910" },
  { name: "Pidilite", industry: "FMCG", location: "Mumbai", companySize: "1,001-5,000", website: "https://pidilite.com", description: "Indian adhesive and construction chemicals company.", founded: "1959" },
  { name: "Marico", industry: "FMCG", location: "Mumbai", companySize: "1,001-5,000", website: "https://marico.com", description: "Indian consumer goods company.", founded: "1990" },
  { name: "Cipla", industry: "Pharmaceuticals", location: "Mumbai", companySize: "10,001+", website: "https://cipla.com", description: "Indian pharmaceutical company.", founded: "1935" },
  { name: "Sun Pharma", industry: "Pharmaceuticals", location: "Mumbai", companySize: "10,001+", website: "https://sunpharma.com", description: "Indian pharmaceutical company.", founded: "1983" },
  { name: "Dr. Reddy's", industry: "Pharmaceuticals", location: "Hyderabad", companySize: "10,001+", website: "https://drreddys.com", description: "Indian pharmaceutical company.", founded: "1984" },
];

const FEATURED_BRANDS = [
  "Google", "Microsoft", "Amazon", "Meta", "Flipkart", "Swiggy", "Zomato",
  "PhonePe", "Razorpay", "CRED", "Nykaa", "Deloitte", "Accenture", "TCS",
  "Infosys", "Wipro", "NVIDIA", "Salesforce", "Adobe", "Zoho", "Zerodha",
  "Zepto", "Blinkit", "Lenskart", "Dream11", "Freshworks",
];

export function buildSeedCompanies() {
  const all = [...SEED_COMPANIES, ...ADDITIONAL_COMPANIES];
  const seen = new Set();
  const out = [];
  all.forEach((c) => {
    if (seen.has(c.name)) return;
    seen.add(c.name);
    const featured = FEATURED_BRANDS.includes(c.name) || c.name.length % 3 === 0;
    out.push({
      name: c.name,
      slug: slugify(c.name),
      industry: c.industry,
      location: c.location,
      companySize: c.companySize,
      description: c.description,
      website: c.website,
      founded: c.founded,
      headquarters: c.location,
      isPartner: false,
      isVerified: featured,
      isFeatured: featured,
      hiringStatus: "unknown",
    });
  });
  return out;
}

// The 27 hand-authored jobs from src/data/jobs.ts (isDemo removed).
export const SEED_JOBS = [
  { title: "Software Development Intern", companyName: "Google", location: "Bengaluru / Remote", type: "INTERNSHIP", workMode: "REMOTE", salaryMin: 35000, salaryMax: 50000, isStipend: true, experience: "0 - 1 year", skills: ["JavaScript", "TypeScript", "Data Structures", "Algorithms"], category: "Software Development", description: "Join our engineering team to work on products used by billions. You'll collaborate with senior engineers, write production code, and learn from world-class mentors.", responsibilities: ["Write clean, maintainable code in modern JavaScript/TypeScript", "Collaborate with cross-functional teams on product features", "Participate in code reviews and design discussions", "Debug and fix issues across the stack"], requirements: ["Pursuing or recent graduate in CS/IT or related field", "Strong fundamentals in data structures and algorithms", "Familiarity with at least one modern framework", "Excellent problem-solving skills"], benefits: ["Competitive stipend", "Mentorship from senior engineers", "Flexible work hours", "Opportunity for full-time conversion"], createdAt: "2026-09-01", deadline: "2026-10-15" },
  { title: "Frontend Developer", companyName: "Flipkart", location: "Bengaluru", type: "FULL_TIME", workMode: "ON_SITE", salaryMin: 1200000, salaryMax: 2200000, experience: "2 - 5 years", skills: ["React", "TypeScript", "Next.js", "CSS"], category: "Software Development", description: "Build delightful user experiences for millions of shoppers. Work on high-scale web applications with modern tooling.", responsibilities: ["Develop responsive, high-performance web applications", "Build reusable component libraries", "Optimize application performance", "Collaborate with designers and product managers"], requirements: ["3+ years of frontend development experience", "Expert in React and TypeScript", "Experience with modern build tools", "Strong understanding of web performance"], benefits: ["Competitive salary", "Health insurance", "ESOPs", "Learning budget"], createdAt: "2026-08-28", deadline: "2026-10-30" },
  { title: "Backend Engineer", companyName: "Razorpay", location: "Bengaluru", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1500000, salaryMax: 3000000, experience: "3 - 6 years", skills: ["Node.js", "Java", "Distributed Systems", "PostgreSQL"], category: "Software Development", description: "Build the payments infrastructure that powers thousands of businesses. Work on distributed systems at scale.", responsibilities: ["Design and implement scalable backend services", "Build and maintain payment processing systems", "Write comprehensive unit and integration tests", "Work on reducing latency and improving reliability"], requirements: ["3+ years building backend systems", "Strong experience with Node.js or Java", "Experience with relational databases", "Understanding of distributed systems"], benefits: ["Attractive compensation", "Health and wellness benefits", "Structured growth path", "Hybrid work model"], createdAt: "2026-08-25", deadline: "2026-11-01" },
  { title: "Data Analyst Intern", companyName: "Meesho", location: "Remote", type: "INTERNSHIP", workMode: "REMOTE", salaryMin: 25000, salaryMax: 35000, isStipend: true, experience: "0 - 1 year", skills: ["SQL", "Python", "Excel", "Data Visualization"], category: "Data Science", description: "Analyze user behavior and business metrics to drive decisions. Work with a data-driven team focused on growth.", responsibilities: ["Analyze large datasets to extract business insights", "Build dashboards and reports for stakeholders", "Collaborate with product and growth teams", "Present findings to leadership"], requirements: ["Strong SQL and Python skills", "Understanding of statistics", "Experience with data visualization tools", "Strong communication skills"], benefits: ["Paid internship", "Remote-friendly", "Mentorship", "Certificate of completion"], createdAt: "2026-08-30", deadline: "2026-10-10" },
  { title: "Full Stack Developer", companyName: "Zoho", location: "Chennai", type: "FULL_TIME", workMode: "ON_SITE", salaryMin: 900000, salaryMax: 1800000, experience: "1 - 4 years", skills: ["React", "Node.js", "MongoDB", "TypeScript"], category: "Software Development", description: "Build end-to-end features for our suite of business applications used by millions worldwide.", responsibilities: ["Design and build full-stack web applications", "Develop RESTful APIs and integrations", "Maintain code quality and documentation", "Collaborate across teams"], requirements: ["1+ years full-stack experience", "Proficiency in React and Node.js", "Experience with NoSQL databases", "Ability to work independently"], benefits: ["Competitive salary", "Comprehensive benefits", "Work-life balance", "Learning opportunities"], createdAt: "2026-09-02", deadline: "2026-10-25" },
  { title: "Product Manager", companyName: "CRED", location: "Bengaluru", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 2500000, salaryMax: 4000000, experience: "4 - 8 years", skills: ["Product Strategy", "Data-driven", "Roadmapping"], category: "Product", description: "Own product initiatives that delight CRED's premium members. Drive product strategy from discovery to launch.", responsibilities: ["Define product vision and roadmap", "Lead cross-functional teams to deliver features", "Use data to inform product decisions", "Interact with members to understand needs"], requirements: ["4+ years in product management", "Experience with consumer apps", "Strong analytical skills", "Excellent communication"], benefits: ["Top-tier compensation", "Health coverage", "Premium Perks", "Flexible work"], createdAt: "2026-08-20", deadline: "2026-10-20" },
  { title: "UI/UX Design Intern", companyName: "Figma", location: "Remote", type: "INTERNSHIP", workMode: "REMOTE", salaryMin: 30000, salaryMax: 40000, isStipend: true, experience: "0 - 1 year", skills: ["Figma", "UI Design", "UX Research", "Prototyping"], category: "Design", description: "Learn design systems and product thinking at a leading design tool company. Create delightful interfaces.", responsibilities: ["Create wireframes and high-fidelity prototypes", "Build and maintain design system components", "Conduct user research and usability testing", "Collaborate with product and engineering"], requirements: ["Portfolio demonstrating design skills", "Proficiency with Figma", "Understanding of UX principles", "Strong visual design sense"], benefits: ["Generous stipend", "Fully remote", "Design mentorship", "Learning stipend"], createdAt: "2026-08-22", deadline: "2026-10-05" },
  { title: "Machine Learning Engineer", companyName: "NVIDIA", location: "Bengaluru", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 3000000, salaryMax: 5000000, experience: "3 - 7 years", skills: ["Python", "PyTorch", "CUDA", "Deep Learning"], category: "AI/ML", description: "Build GPU-accelerated machine learning solutions that push the boundaries of AI computing.", responsibilities: ["Develop and optimize ML models", "Work on GPU-accelerated training pipelines", "Contribute to CUDA-based optimizations", "Collaborate with research teams"], requirements: ["Strong Python and ML background", "Experience with PyTorch/TensorFlow", "Understanding of GPU programming", "MS/PhD preferred, or equivalent experience"], benefits: ["Competitive pay", "RSUs", "Health benefits", "Cutting-edge work"], createdAt: "2026-08-18", deadline: "2026-10-28" },
  { title: "Marketing Intern", companyName: "Swiggy", location: "Bengaluru / Remote", type: "INTERNSHIP", workMode: "HYBRID", salaryMin: 15000, salaryMax: 25000, isStipend: true, experience: "0 - 1 year", skills: ["Marketing", "Content", "Social Media", "Analytics"], category: "Marketing", description: "Support consumer marketing campaigns that reach millions of users. Learn the full spectrum of growth marketing.", responsibilities: ["Assist in planning and executing marketing campaigns", "Create content for social media channels", "Analyze campaign performance metrics", "Coordinate with agencies and partners"], requirements: ["Pursuing marketing/business degree", "Strong writing skills", "Familiarity with social media platforms", "Organized and detail-oriented"], benefits: ["Paid internship", "Real campaign experience", "Mentorship", "Potential PPO"], createdAt: "2026-09-01", deadline: "2026-10-12" },
  { title: "Financial Analyst", companyName: "American Express", location: "Gurugram", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1000000, salaryMax: 1800000, experience: "1 - 4 years", skills: ["Financial Modeling", "Excel", "SQL", "Analytics"], category: "Finance", description: "Analyze financial performance and support business decisions across the company's global operations.", responsibilities: ["Build financial models and forecasts", "Analyze business performance metrics", "Prepare management reports", "Support budget planning"], requirements: ["Finance or related degree", "Strong financial modeling skills", "Proficiency in Excel", "Experience with SQL preferred"], benefits: ["Competitive compensation", "Global exposure", "Learning programs", "Wellness benefits"], createdAt: "2026-08-19", deadline: "2026-10-18" },
  { title: "Product Design Intern", companyName: "Canva", location: "Remote", type: "INTERNSHIP", workMode: "REMOTE", salaryMin: 28000, salaryMax: 38000, isStipend: true, experience: "0 - 1 year", skills: ["Figma", "Design Systems", "Interaction Design"], category: "Design", description: "Create intuitive, delightful design experiences for one of the world's most popular design tools.", responsibilities: ["Create interaction flows and prototypes", "Contribute to our design system", "Participate in design critiques", "Ship features with the product team"], requirements: ["Strong portfolio", "Proficiency in Figma", "Understanding of design systems", "Product thinking"], benefits: ["Paid internship", "Remote work", "Design mentorship", "Free Canva perks"], createdAt: "2026-08-26", deadline: "2026-10-08" },
  { title: "Cloud Solutions Architect", companyName: "Amazon", location: "Hyderabad", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 2800000, salaryMax: 4500000, experience: "4 - 8 years", skills: ["AWS", "Cloud Architecture", "Kubernetes", "DevOps"], category: "Software Development", description: "Architect cloud solutions for enterprise customers on AWS. Design scalable, secure infrastructure.", responsibilities: ["Design cloud architectures for customers", "Implement scalable AWS solutions", "Optimize cost and performance", "Lead technical workshops"], requirements: ["AWS certifications preferred", "4+ years architecture experience", "Deep Kubernetes knowledge", "Excellent communication"], benefits: ["Industry-leading pay", "Amazon benefits", "Career growth", "Relocation support"], createdAt: "2026-08-15", deadline: "2026-10-22" },
  { title: "Cybersecurity Analyst", companyName: "Deloitte", location: "Mumbai", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1200000, salaryMax: 2000000, experience: "2 - 5 years", skills: ["Security", "Risk Assessment", "Compliance", "Auditing"], category: "Cybersecurity", description: "Protect client data and systems from cyber threats. Work at the intersection of business and security.", responsibilities: ["Conduct security assessments and audits", "Design security controls and frameworks", "Monitor for threats and vulnerabilities", "Advise clients on security best practices"], requirements: ["2+ years in cybersecurity", "Relevant certifications (CISSP, CISM)", "Strong risk assessment skills", "Knowledge of compliance frameworks"], benefits: ["Competitive salary", "Global projects", "Certification support", "Health benefits"], createdAt: "2026-08-12", deadline: "2026-10-19" },
  { title: "HR Operations Intern", companyName: "Urban Company", location: "Gurugram", type: "INTERNSHIP", workMode: "ON_SITE", salaryMin: 12000, salaryMax: 18000, isStipend: true, experience: "0 - 1 year", skills: ["HR", "Communication", "MS Excel"], category: "HR", description: "Support HR operations and gain hands-on experience in people management at a fast-growing startup.", responsibilities: ["Assist with onboarding and offboarding", "Support employee engagement activities", "Maintain HR records and databases", "Coordinate interviews and scheduling"], requirements: ["HR/MBA student preferred", "Strong communication skills", "Proficiency in Excel", "Organized and dependable"], benefits: ["Paid internship", "Real HR exposure", "Mentorship", "PPO opportunity"], createdAt: "2026-08-24", deadline: "2026-10-01" },
  { title: "Business Development Associate", companyName: "Porter", location: "Mumbai", type: "FULL_TIME", workMode: "ON_SITE", salaryMin: 400000, salaryMax: 700000, experience: "0 - 2 years", skills: ["Sales", "Negotiation", "Client Management"], category: "Business Development", description: "Drive business growth by building relationships with logistics partners and enterprise clients.", responsibilities: ["Acquire new business partners", "Build relationships with enterprise clients", "Negotiate contracts and pricing", "Track and report sales metrics"], requirements: ["Recent graduate in business", "Strong communication skills", "Drive and self-motivation", "Negotiation skills"], benefits: ["Attractive incentives", "Career growth", "Team culture", "Health benefits"], createdAt: "2026-08-27", deadline: "2026-10-14" },
  { title: "Sales Executive", companyName: "Salesforce", location: "Mumbai", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1200000, salaryMax: 2000000, experience: "2 - 5 years", skills: ["Sales", "CRM", "Software Sales"], category: "Sales", description: "Sell cloud-software solutions to enterprise customers and help businesses transform digitally.", responsibilities: ["Manage a pipeline of enterprise accounts", "Present and demo Salesforce solutions", "Negotiate and close deals", "Build long-term client relationships"], requirements: ["2+ years in software sales", "Strong consultative selling skills", "CRM experience", "Excellent presentation skills"], benefits: ["Commission structure", "Salesforce benefits", "Training", "Travel opportunities"], createdAt: "2026-08-16", deadline: "2026-10-16" },
  { title: "Operations Associate", companyName: "Zepto", location: "Mumbai", type: "FULL_TIME", workMode: "ON_SITE", salaryMin: 500000, salaryMax: 900000, experience: "0 - 3 years", skills: ["Operations", "Analytics", "Supply Chain"], category: "Operations", description: "Keep Zepto's 10-minute promise alive. Optimize dark store operations and delivery performance.", responsibilities: ["Manage dark store operations", "Optimize inventory and staffing", "Analyze operational metrics", "Improve delivery efficiency"], requirements: ["Strong analytical skills", "MBA preferred", "Comfort with data", "Operations experience a plus"], benefits: ["Competitive pay", "Rapid growth", "Performance bonuses", "Learning culture"], createdAt: "2026-08-29", deadline: "2026-10-11" },
  { title: "Content Writer", companyName: "Zomato", location: "Gurugram / Remote", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 600000, salaryMax: 1000000, experience: "1 - 3 years", skills: ["Writing", "SEO", "Content Strategy"], category: "Content", description: "Craft engaging content for India's favorite food delivery brand. Write across app, blog and social channels.", responsibilities: ["Write engaging copy for app and website", "Create content for marketing campaigns", "Optimize content for SEO", "Maintain brand voice and style"], requirements: ["1+ years content writing experience", "Excellent English writing skills", "SEO knowledge", "Portfolio of work"], benefits: ["Competitive salary", "Meal perks", "Health benefits", "Creativity freedom"], createdAt: "2026-08-21", deadline: "2026-10-09" },
  { title: "Data Engineer", companyName: "PhonePe", location: "Bengaluru", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1800000, salaryMax: 3200000, experience: "3 - 6 years", skills: ["Spark", "SQL", "Python", "Data Pipelines"], category: "Data Science", description: "Build data platforms that process billions of transactions. Power business intelligence at scale.", responsibilities: ["Design and build data pipelines", "Optimize data processing at scale", "Build data lake and warehouse infrastructure", "Collaborate with data scientists"], requirements: ["3+ years data engineering experience", "Strong SQL and Spark", "Experience with Python", "Knowledge of cloud data services"], benefits: ["Competitive compensation", "Large-scale impact", "Learning budget", "Health insurance"], createdAt: "2026-08-23", deadline: "2026-10-23" },
  { title: "Investment Banking Analyst", companyName: "Goldman Sachs", location: "Mumbai", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1800000, salaryMax: 3000000, experience: "0 - 3 years", skills: ["Finance", "Valuation", "Modeling", "Excel"], category: "Finance", description: "Support M&A transactions and capital raising for clients across sectors in a fast-paced environment.", responsibilities: ["Build financial models and valuations", "Prepare pitch books and presentations", "Support deal execution and due diligence", "Research industry trends"], requirements: ["Strong academic background in finance", "Advanced Excel skills", "Way with numbers", "Ability to work under pressure"], benefits: ["High compensation", "Global exposure", "Training programs", "Career progression"], createdAt: "2026-08-14", deadline: "2026-10-21" },
  { title: "iOS Developer Intern", companyName: "Razorpay", location: "Bengaluru", type: "INTERNSHIP", workMode: "HYBRID", salaryMin: 22000, salaryMax: 30000, isStipend: true, experience: "0 - 1 year", skills: ["Swift", "iOS", "UIKit", "SwiftUI"], category: "Software Development", description: "Build beautiful iOS experiences with a passionate product team. Learn modern iOS development.", responsibilities: ["Develop iOS app features in Swift", "Write unit tests", "Collaborate with designers", "Ship updates to the App Store"], requirements: ["Basic Swift knowledge", "Understanding of UIKit/SwiftUI", "Great attitude and eagerness to learn", "Portfolio/GitHub welcome"], benefits: ["Paid internship", "Mentorship", "Flexible hours", "PPO potential"], createdAt: "2026-09-03", deadline: "2026-10-06" },
  { title: "Mobile Product Designer", companyName: "Nykaa", location: "Mumbai", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 1500000, salaryMax: 2500000, experience: "3 - 6 years", skills: ["Figma", "Mobile Design", "Design Systems"], category: "Design", description: "Design delightful mobile shopping experiences for beauty enthusiasts across India.", responsibilities: ["Design mobile app experiences", "Create high-fidelity prototypes", "Build and maintain design systems", "Collaborate with product and eng"], requirements: ["3+ years product design experience", "Strong mobile design portfolio", "Figma expertise", "User-centered approach"], benefits: ["Competitive salary", "Employee discounts", "Health benefits", "Creative team"], createdAt: "2026-08-17", deadline: "2026-10-17" },
  { title: "Software Engineer (Full Stack)", companyName: "Atlassian", location: "Bengaluru", type: "FULL_TIME", workMode: "HYBRID", salaryMin: 2000000, salaryMax: 3500000, experience: "3 - 7 years", skills: ["React", "Java", "GraphQL", "AWS"], category: "Software Development", description: "Build tools that help teams everywhere do their best work. Own features end-to-end.", responsibilities: ["Develop full-stack features", "Build scalable APIs with GraphQL", "Contribute to architecture decisions", "Mentor junior engineers"], requirements: ["3+ years software engineering experience", "Strong React and Java skills", "Experience with GraphQL and AWS", "Collaborative mindset"], benefits: ["Competitive pay", "Share program", "Generous leave", "Growth opportunities"], createdAt: "2026-08-13", deadline: "2026-10-20" },
  { title: "Research & Development Engineer", companyName: "Tesla", location: "Hyderabad", type: "FULL_TIME", workMode: "ON_SITE", salaryMin: 3000000, salaryMax: 5000000, experience: "4 - 8 years", skills: ["C/C++", "Embedded Systems", "AI", "Robotics"], category: "Software Development", description: "Build cutting-edge embedded systems and AI solutions for next-generation vehicles.", responsibilities: ["Develop embedded software systems", "Implement AI/ML algorithms", "Test and validate systems", "Collaborate across engineering teams"], requirements: ["4+ years embedded systems experience", "Strong C/C++ proficiency", "AI/ML background", "Rigorous engineering mindset"], benefits: ["Competitive salary", "RSUs", "Innovation culture", "Health benefits"], createdAt: "2026-08-11", deadline: "2026-10-26" },
];

// Additional jobs generated to cover extra roles (rewritten without demo copy).
export const EXTRA_JOB_DEFS = [
  { title: "DevOps Engineer", category: "Software Development", skills: ["Docker", "Kubernetes", "CI/CD", "AWS"] },
  { title: "QA Engineer", category: "Software Development", skills: ["Testing", "Selenium", "Automation"] },
  { title: "Android Developer", category: "Software Development", skills: ["Kotlin", "Android", "Java"] },
  { title: "Business Analyst", category: "Business Development", skills: ["SQL", "Excel", "Requirements"] },
  { title: "Account Manager", category: "Sales", skills: ["CRM", "Communication", "Clients"] },
  { title: "Search Analyst", category: "Data Science", skills: ["SQL", "Python", "Analytics"] },
];

export function buildSeedJobs(companies) {
  const jobs = SEED_JOBS.map((j) => j);
  const usedCompanyNames = new Set(SEED_JOBS.map((j) => j.companyName));
  const pool = companies.filter((c) => !usedCompanyNames.has(c.name));
  const now = Date.now();
  EXTRA_JOB_DEFS.forEach((j, idx) => {
    if (pool.length === 0) return;
    const company = pool[idx % pool.length];
    const isIntern = idx % 3 === 0;
    jobs.push({
      title: isIntern ? `${j.title} Intern` : j.title,
      companyName: company.name,
      location: company.location + (idx % 2 === 0 ? " / Remote" : ""),
      type: isIntern ? "INTERNSHIP" : idx % 2 === 0 ? "FULL_TIME" : "CONTRACT",
      workMode: idx % 3 === 0 ? "REMOTE" : "HYBRID",
      salaryMin: isIntern ? 15000 : 800000,
      salaryMax: isIntern ? 25000 : 1500000,
      isStipend: isIntern,
      experience: isIntern ? "0 - 1 year" : "1 - 4 years",
      skills: j.skills,
      category: j.category,
      description: `Join ${company.name} as a ${j.title}. Drive meaningful impact across teams while growing your craft in a fast-paced environment.`,
      responsibilities: ["Collaborate with cross-functional teams", "Own end-to-end delivery of assigned work", "Write quality, maintainable output", "Continuously learn and improve"],
      requirements: ["Relevant degree or equivalent experience", "Strong foundational skills", "Good communication", "Eagerness to learn"],
      benefits: ["Competitive compensation", "Learning culture", "Growth opportunities", "Team events"],
      createdAt: new Date(now - idx * 86400000 * 2).toISOString().slice(0, 10),
      deadline: new Date(now + 30 * 86400000).toISOString().slice(0, 10),
    });
  });
  return jobs;
}

export function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}